### ISSUE TITLE
Splitting out the shell lesson

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/datacarpentry#119]
This issue is for managing the splitting out of the shell lesson.

## Background

I believe that the shell lesson was seeded with the Software Carpentry material in Sping 2014. This means that during the splitting out we should attempt get the history associated with the SWC lesson up to that point. After a little investigating it looks like the seeding SWC commit was likely https://github.com/swcarpentry/bc/commit/e2f3f3de9961df54bfc55e4062a5f4159442c0cc#diff-4238a7b516a6fc54736baf2ec23529fa.

## Process

Due to path changes and history that had been lost in previous SWC reorganizations simply starting at https://github.com/swcarpentry/bc/commit/e2f3f3de9961df54bfc55e4062a5f4159442c0cc#diff-4238a7b516a6fc54736baf2ec23529fa will not give us the full history. Ideally, we would be able to use @wking's excellent work pulling out all fo the history into the new SWC shell lesson (https://github.com/swcarpentry/shell-novice/). However it isn't clear if this will work cleanly because it appears that the relevant commit (https://github.com/swcarpentry/shell-novice/commit/ae34f571727a036f2e0216df9ec945294bee701b) was added in later than it had originally occured as part of the SWC efforts to reassemble the history.

## To Do

- [x] Find point of divergence from SWC lesson
- [x] Bring in SWC history
- [x] Merge in DC changes

**Comment by ethanwhite** [comment]
OK, there is now a draft of this split for folks to look at:
https://github.com/ethanwhite/dc-shell-ecology

I create this using the following:

```
echo "Cloning SWC repo"
git clone git@github.com:swcarpentry/shell-novice.git
cd shell-novice

echo "Checking out diverging commit and creating branch"
git checkout ae34f57
git checkout -b master

echo "Adding Data Carpentry branch"
git remote add datacarp git@github.com:datacarpentry/datacarpentry.git
git checkout --orphan dcshell
git rm -rf .
git fetch datacarp
git merge datacarp/master

echo "Filtering the lesson"
git filter-branch --prune-empty --subdirectory-filter lessons/shell/ dcshell

echo "Merging SWC and DC material"
git checkout master
git merge dcshell
git checkout --theirs *
git add -u
git commit -m "Merging Software Carpentry and Data Carpentry history"
git rm -rf creatures/ filesystem/ finding/ molecules/ scripting/ gen-nene.py gen-sequence.py guide.md reference.md
git commit -m "Remove files and directories not used by Data Carpentry"

echo " Adding files and history for CONTRIBUTING, CONTRIBUTORS, LICENSE, README & .gitignore"
git cherry-pick b433f2c4b444191df6b0b9382737b5f6eb3a1f40 d2fe4756e20a44a814ce93d38271f4cd41828173 e23865af07f297ca0b01e968968eafebecc2e7e3 4ac75d15c7265a58f6d101a3bde3d50bf02b9924 b90e67ae94176b074916f9c10cc18e2deafb20ce c5dd7666f662b04251cee6ec4622286dee06b7c5 9aed23f920fe1abd31add5d34c76b8d1fee17ba5 dd1988ca2ff671150d1c4310b934f3c8284e3eb9 67f79c617006ee1452240fefdc3b203349cf3ca6 d9820636810b9630da26de24dddfab79a60107fc b7dbb4e983e06629f97f9949c7480634436dce55 6eedff03c209b56da83eeb3da62235c4ac3c2338 4338a548493411b92d945b829923b053141d743e 00e12d1431311825e44093c5d4677a6e21cf94d4 6182be915474187829dbb7b5e0719660671d442f e04f7e1936b82c9ba25bee37ea897db168036632 0b6ac9ec2421c0abd3639b0b84440ca14afa375c
```

I've done some spot checking and it looks like I might have all of the relevant pieces, but I'm not sure.

@wking - can you take a look at this and see if I've successfully grabbed all of the relevant SWC history up to the point of divergence (and, ideally, no extra history).

@kcranston - can you take a look at this and see if I've managed to keep the final state of the material in the correct state and if all of the DC history is in place.

@tracykteal - can you see if this fits what you were generally envisioning for the split.

Thanks to all in advance.

**Comment by kcranston** [comment]
This looks good to me (in terms of keeping history from SWC and DC). The whole lesson needs a massive re-organization to integrate the contents of the shell.md file that contains the DC lesson into the  (much more detailed) 0\d-.*\.md files. But, that's a separate issue.

**Comment by wking** [comment]
On Sat, Feb 07, 2015 at 11:17:03AM -0800, Ethan White wrote:
> OK, there is now a draft of this split for folks to look at:

This looks pretty good to me.

> echo "Adding Data Carpentry branch"
> git remote add datacarp git@github.com:datacarpentry/datacarpentry.git
> git checkout --orphan dcshell
> git rm -rf .
> git fetch datacarp
> git merge datacarp/master
> 
> echo "Filtering the lesson"
> git filter-branch --prune-empty --subdirectory-filter lessons/shell/ dcshell
> 
> echo "Merging SWC and DC material"
> git checkout master
> git merge dcshell
> git checkout --theirs *
> git add -u
> git commit -m "Merging Software Carpentry and Data Carpentry history"
> git rm -rf creatures/ filesystem/ finding/ molecules/ scripting/ gen-nene.py gen-sequence.py guide.md reference.md
> git commit -m "Remove files and directories not used by Data Carpentry"

Instead of merging and then cleaning out the SWC-only stuff, I'd
probably remove the SWC-stuff from the SWC branch, and then graft the
DC branch onto that.  With your work, that's:

  $ git checkout -b swc-shell-root ae34f57  # fork point from SWC's shell-novice
  $ git rm -rf creatures/ filesystem/ finding/ molecules/ scripting/ gen-nene.py gen-sequence.py guide.md
  $ git commit -m "Remove files and directories not used by Data Carpentry"

I've left reference.md, because it might have been the seed for DC's
cheatsheets/shell.md (although the content looked pretty different).
Now pull on the oldest DC commit from your shell filter-branch,

  $ git cherry-pick 4ca78f7
  $ git rm -rf .
  $ git read-tree 4ca78f7
  $ git checkout -- .
  $ git cat-file -p 9aa1327:cheatsheets/shell.md > reference.md
  $ git add reference.md
  $ git cherry-pick --continue

Check the new commit:

  $ git diff --stat 4ca78f7..HEAD
   reference.md | 105 +++++++++++++++++++++++++++++++++++++++++++
   1 file changed, 105 insertions(+)
  $ git ls-tree 9aa1327 -- cheatsheets/shell.md
  100644 blob 50792da8733dd64f5d065bdc43ab4ffbbf0e5eb6    cheatsheets/shell.md
  $ git ls-tree HEAD -- reference.md
  100644 blob 50792da8733dd64f5d065bdc43ab4ffbbf0e5eb6    reference.md

Now attach the rest of the DC history (after 4ca78f7) from your
rebased branch:

  $ git checkout -b dc-shell d9cb833
  $ git rebase -p --onto swc-shell-root 4ca78f7

Look at the grafted history:

  $ git log --graph --topo-order --oneline --decorate
  *   176a23f (HEAD, dc-shell) Merge pull request #103 from sr320/patch-1
  |\
  | * e93231b Changed contraction to two words, added a few spaces for formatting
  * |   6a0f71a Merge pull request #106 from anakarinarm/patch-1
  |\ \
  | * | b2019d6 Update 04-loop.md
  | |/
  * | d67d185 Added to make a more complete bullet
  |/
  * cfc9b11 a few more rogue data files deleted
  * bdfe6a8 cleaning comments
  * f838f56 Changes regarding Tracy's pull
  *   e7570fe Merge branch 'master' of https://github.com/datacarpentry/datacarpentry into bashtest
  |\
  | * 56fe6e0 fixed man text formatting
  | * 9dbdb23 added man command to beginning of shell lesson
  * | 91e140e man-related changes in lessons 01 and 06
  * | 0da3cd8 Marking work for tomorrow
  * | e8a7a13 Added sublime to text editors
  * | b1b549a Added info about man command and file naming with whitespaces
  |/
  * c721275 (swc-shell-root) finally adding shell lessons and cheatsheets for shell and sql
  * 704d1f7 Remove files and directories not used by Data Carpentry
  * ae34f57 Modifying all raw Markdown files to use class attributes for code blocks
  …

Did we miss any cheat-sheet commits?

  $ git log --oneline --follow datacarp/master -- cheatsheets/shell.md
  1d0f8d0 Add blank lines after markdown headings
  9aa1327 finally adding shell lessons and cheatsheets for shell and sql

Where does 1d0f8d0 fit in?

  $ git log -1 --date=iso --pretty=format:'%h %ad %s' 1d0f8d0
  1d0f8d0 2014-08-01 14:13:06 -0600 Add blank lines after markdown headings
  $ git log --graph --date-order --date=iso --pretty=format:'%h %ad %s'
  *   176a23f 2014-11-14 14:27:38 -0500 Merge pull request #103 from sr320/patch-1
  |\
  | * e93231b 2014-11-14 10:52:31 -0800 Changed contraction to two words, added a few spaces for formatting
  * |   6a0f71a 2014-11-14 14:21:48 -0500 Merge pull request #106 from anakarinarm/patch-1
  |\ \
  * | | d67d185 2014-11-14 10:52:16 -0800 Added to make a more complete bullet
  | |/
  |/|
  | * b2019d6 2014-11-14 10:52:47 -0800 Update 04-loop.md
  |/
  * cfc9b11 2014-08-06 14:33:24 -0400 a few more rogue data files deleted
  * bdfe6a8 2014-07-23 18:46:55 +0200 cleaning comments

So it should land between bdfe6a8 and cfc9b11.  Graft it in:

  $ git checkout -b wip bdfe6a8
  $ git cherry-pick 1d0f8d0
  $ git rm CONTRIBUTORS.md
  $ git cherry-pick --continue
  $ git checkout dc-shell
  $ git rebase -p wip

Check the graft point:

  $ git log --graph --topo-order --oneline --decorate | grep -3 'Add blank lines after markdown headings'
  * | 65eb2c4 Added to make a more complete bullet
  |/
  * 1694220 a few more rogue data files deleted
  * 5abb875 (wip) Add blank lines after markdown headings
  * bdfe6a8 cleaning comments
  * f838f56 Changes regarding Tracy's pull
  *   e7570fe Merge branch 'master' of https://github.com/datacarpentry/datacarpentry into bashtest

Looks good.  Remove the temporary branches:

  $ git branch -d wip swc-shell-root

Then continue where you left off:

> echo " Adding files and history for CONTRIBUTING, CONTRIBUTORS, LICENSE, README & .gitignore"
> git cherry-pick b433f2c4b444191df6b0b9382737b5f6eb3a1f40 d2fe4756e20a44a814ce93d38271f4cd41828173 e23865af07f297ca0b01e968968eafebecc2e7e3 4ac75d15c7265a58f6d101a3bde3d50bf02b9924 b90e67ae94176b074916f9c10cc18e2deafb20ce c5dd7666f662b04251cee6ec4622286dee06b7c5 9aed23f920fe1abd31add5d34c76b8d1fee17ba5 dd1988ca2ff671150d1c4310b934f3c8284e3eb9 67f79c617006ee1452240fefdc3b203349cf3ca6 d9820636810b9630da26de24dddfab79a60107fc b7dbb4e983e06629f97f9949c7480634436dce55 6eedff03c209b56da83eeb3da62235c4ac3c2338 4338a548493411b92d945b829923b053141d743e 00e12d1431311825e44093c5d4677a6e21cf94d4 6182be915474187829dbb7b5e0719660671d442f e04f7e1936b82c9ba25bee37ea897db168036632 0b6ac9ec2421c0abd3639b0b84440ca14afa375c

Check the CONTRIBUTORS.md change we dropped from 1d0f8d0:

  $ git show 1d0f8d0 -- CONTRIBUTORS.md
  …
   ### Biology
  +
   Data is from the paper…
  …

Do we have those in the reconstructed history?

  $ grep -2 Biology CONTRIBUTORS.md
  ## Data

  ### Biology
  Data is from the paper…

Lets add them back in:

  $ git cherry-pick 1d0f8d0
  $ grep -2 Biology CONTRIBUTORS.md
  ## Data

  ### Biology

  Data is from the paper…

So that looks good.  If we had time, it would be nice to go back and
inject the metadata commits (for CONTRIBUTING, CONTRIBUTORS, LICENSE,
README & .gitignore) into the other history (as I did with the
cheat-sheet part of 1d0f8d0), since then the chronology would be right
and we wouldn't have to split 1d0f8d0 into two commits (one with the
cheat-sheet edits, and that last cherry-pick for the CONTRIBUTORS.md
edits).  The procedure is simple, but I don't know if it's worth the
time.  You might also want to filter the CONTRIBUTORS.md changes to
only include folks contributing to the shell lesson, but again, maybe
not worth the time.  Anyhow, I've pushed my branch up at:

  git://github.com/wking/shell-novice.git dc-shell

if you want to grab it and check it over.

**Comment by wking** [comment]
On Sat, Feb 07, 2015 at 12:48:48PM -0800, Karen Cranston wrote:
> The whole lesson needs a massive re-organization to integrate the
> contents of the shell.md file that contains the DC lesson into the
> (much more detailed) 0\d-.*\.md files. But, that's a separate issue.

In my take, I dumped the 0*.md files before grafting on the DC stuff
[1].

[1]: https://github.com/wking/shell-novice/commit/c7212758b9289ce2cffdee2cf72bee41e95b349d

**Comment by ethanwhite** [comment]
Thanks @wking! You truly are a git wizard.

@tracykteal - why don't you take a look at @wking's version. If you're happy and no one else has any objections I think this one ready to go.

**Comment by tracykteal** [comment]
Thanks so much @ethanwhite and @wking! This looks good to me. I agree it's ready to go. @kcranston a lesson update is on my immediate radar.

**Comment by ethanwhite** [comment]
OK, this is now available in a separate repo:
https://github.com/datacarpentry/shell-ecology

Thanks again @wking!
