### ISSUE TITLE
having species column name in surveys.csv and species.csv file name is confusing

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/datacarpentry#121]
In the data it's confusing to have a 'species' column in the surveys.csv dataset and a species.csv file. It might be good to rename the 'species' column in surveys.csv to something like 'speciesID'

**Comment by tracykteal** [comment]
Alternatively or in addition, we could rename the species.csv file

**Comment by fmichonneau** [comment]
I agree it would be good to rename the column speciesID or species_id.

**Comment by kcranston** [comment]
I agree about the confusion, and I think the most confusing part is that there are two species columns as well as a species table. The fact that the species column joins to a column with a different name is actually a good thing in terms of teaching how JOIN works.

**Comment by kcranston** [comment]
So I vote for renaming the species table (and file) rather than the column IDs. Need to check provenance, though - what is that file called on the Ecological Archives site and do we need to make sure we update the readme with the fact that we have changed it?

**Comment by ethanwhite** [comment]
I personally lean towards renaming the column to speciesID as @tracykteal and @fmichonneau suggested. It's true that the different column names help demonstrate a point about joins. But, 1) these are novices so I'm not sure we really need to illustrate this point instead of mentioning it, and 2) I can't think of an equivalently reasonable name for the file/table.

**Comment by fmichonneau** [comment]
this is now fixed in the newer version of the dataset that @ethanwhite has uploaded on figshare. Both species.csv and surveys.csv have a column species_id.
