### ISSUE TITLE
In lessons/R, why discourage names with dots in them?

### ISSUE THREAD

**Issue by plijnzaad** [datacarpentry/datacarpentry#133]
Dear all,

I would have hoped that there is a mechanism for discussing big or controversial changes prior to actually making them, like wikipedia has with the Talk page. (And then preferably per directory or file, since having just one list of issues like could quickly becoming overwhelming).  The reason is of course that you don't want to anger people or do lots of edits that will never be accepted.

anyway, here is one such thing: in

https://github.com/plijnzaad/datacarpentry/blob/master/lessons/R/01-intro-to-R.Rmd

the use of names with dots in is discouraged. Why? They are used exceedingly often, and should at least be 'explained'. And some people/projects actually discourage the use of underscores (since they expand to '<-' in emacs ...)

**Comment by r-gaia-cs** [comment]
Hi @plijnzaad,

> I would have hoped that there is a mechanism for discussing big or controversial changes prior to actually making them, like wikipedia has with the Talk page.

You can use issues, as you did, for that.

> (And then preferably per directory or file, since having just one list of issues like could quickly becoming overwhelming).

By default, you only get email from issues that you reported or subscribed.
This can avoid overwhelming.

> in
> 
> https://github.com/plijnzaad/datacarpentry/blob/master/lessons/R/01-intro-to-R.Rmd
> 
> the use of names with dots in is discouraged. Why?

Probably because dots are used in many programming languages as delimiter for
atributes or methods in object oriented programming.
For example, `foo.bar` in Python means the attribute or method `bar` from
class/object `foo` instead of the variable or function named `foo.bar`.
I know that in R this isn't the case but for novices that could be learning
Python and R at the same time is better to avoid misunderstanding
using names with dots.

**Comment by plijnzaad** [comment]
> Probably because dots are used in many programming languages

Yes, of course, I know, but all of R is absolutely awash with dotted names, so people will have to get used to them right anyway, and they have to be explained properly. 

Do we have something like a coding style, or should we? I think the [Google R Style Guide](https://google-styleguide.googlecode.com/svn/trunk/Rguide.xml) is pretty decent, and they actually prefer dots and disfavour underscores.

**Comment by fmichonneau** [comment]
I started a pull request to add why dots are not recommended in variable
names. I also added a sentence on style guides.
